/*
Copyright 2017 Microsoft
Permission is hereby granted, free of charge, to any person obtaining a copy of this software
and associated documentation files (the "Software"), to deal in the Software without restriction,
including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH
THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

//import "inspectable.idl";
//import "Windows.Foundation.idl";

import "oaidl.idl";
import "unknwn.idl";

#define COMPONENT_VERSION 1.0


[
    uuid (35C574E4-ACED-4ADB-A040-0BE1AF72B7B3),
    version(1.0),
    pointer_default(unique),
]
interface SystemConfiguratorProxyInterface
{

    // context_handle_noserialize in acf for RPC to call rundown when the client goes away
    typedef [context_handle] void* PCONTEXT_HANDLE_TYPE;
    typedef [ref] PCONTEXT_HANDLE_TYPE * PPCONTEXT_HANDLE_TYPE;

    //
    // RPC methods to retrieve/clean client context
    //
    void RemoteOpen([in] handle_t hBinding,[out] PPCONTEXT_HANDLE_TYPE pphContext);
    void RemoteClose([in, out] PPCONTEXT_HANDLE_TYPE pphContext);

    HRESULT SendRequest([in] UINT32 requestType, [in] BSTR request, [out] UINT32* responseType, [out] BSTR* response);
}
